# Generated by Django 4.1 on 2022-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_alter_post_author_alter_post_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="body", field=models.TextField(),
        ),
    ]
